language: node_js

node_js:
  - 'lts/*'

branches:
  only:
    - master
    - dev
    - /(?i)^feature\/\S+$/

before_install: npm install -g npm

install: npm ci

script: npm test

notifications:
  email:
    on_success: never
    on_failure: always
